### ISSUE TITLE
Block regen issue

### ISSUE THREAD

**Issue by OverlordFreddo** [mastercake10/CustomOreGen#49]
### What steps will reproduce the issue?  
1. Update to Paper-86 (MC: 1.19.1)
2. Attempt to mine blocks

### What was supposed to happen?
Defined blocks should be spawned instead of vanilla blocks.

### What happened instead? 
Vanilla blocks spawn intermittently but not always instead of defined blocks 

### What version of this plugin are you using?  
 Appears as CustomOreGen v1.15.26-SNAPSHOT (CustomOreGen-1.3.32-SNAPSHOT.jar)

### What Spigot version are you using? Paste the output of /version below.  
```This server is running Paper version git-Paper-86 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: 4a4ee79)
You are running the latest version
Previous version: git-Paper-77 (MC: 1.19)
```

### What plugins do you have installed? Paste the output of /plugins below.  
```
Plugins (43): AdvancedRegionMarket, AuctionHouse, BetterFood, BlueMap, BottledExp, ChatItem, ChestShop, ChestSort,
CMILib, CoreProtect, CustomOreGen, Elevators, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), 
Graves, Harbor, HeadsPlus, JukeBox, LuckPerms, LWC, LWCTrust, mcMMO, Minepacks, MobsToEggs, MoneyFromMobs,
Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, MyCommand, NoteBlockAPI,
RHLeafDecay, Sickle, SilkSpawners, TempFly, Vault, VeinMiner, ViaBackwards, ViaVersion, WorldBorder, WorldGuard
```

### Are any errors related to this plugin in your console or logs? If so, paste below.  
No errors

### Any additional information that you would like to provide that may be relevant to the issue?

I realise that some of the values in the config are quite low but that does not explain the vanilla stone and cobblestone blocks.

Generator section of config:
```
generators:
  generator1:
    label: "standard"
    blocks:
    - COBBLED_DEEPSLATE:68.0
    - DEEPSLATE_IRON_ORE:5.5
    - DEEPSLATE_COAL_ORE:5.5
    - DEEPSLATE_COPPER_ORE:5.5
    - DEEPSLATE_GOLD_ORE:5.5
    - DEEPSLATE_DIAMOND_ORE:1.5
    - DEEPSLATE_REDSTONE_ORE:5.0
    - DEEPSLATE_EMERALD_ORE:1.5
    - LAPIS_ORE:2.0
    permission: ''
    unlock_islandLevel: 0
```
Image of cobble generator which was working before updating paper to 1.19.1:
![image](https://user-images.githubusercontent.com/7680423/181707121-81669600-ae59-472e-afeb-4bd8aa796a19.png)
